const fs = require('fs');
const path = require('path');

const CN_NAMES = {
  // 舰队Collection
  'kaga_(kancolle)': '加贺',
  'shimakaze_(kancolle)': '岛风',
  'shigure_(kancolle)': '时雨',
  'hibiki_(kancolle)': '响',
  'akagi_(kancolle)': '赤城',
  'zuikaku_(kancolle)': '瑞鹤',
  'shoukaku_(kancolle)': '翔鹤',
  'kongou_(kancolle)': '金刚',
  'yamato_(kancolle)': '大和',
  'iowa_(kancolle)': '衣阿华',
  'kashima_(kancolle)': '鹿岛',
  'hamakaze_(kancolle)': '浜风',
  'prinz_eugen_(kancolle)': '欧根亲王',
  'atago_(kancolle)': '爱宕',
  'suzuya_(kancolle)': '铃谷',

  // 偶像大师
  'shibuya_rin': '涩谷凛',
  'higuchi_madoka': '樋口圆香',
  'kisaragi_chihaya': '如月千早',
  'hoshii_miki': '星井美希',
  'ichinose_shiki': '一之濑志希',
  'takagaki_kaede': '高�的楓',
  'nitta_minami': '新田美奈实',
  'shimamura_uzuki': '岛村卯月',
  'honda_mio': '本田未央',
  'shijou_takane': '四条贵音',
  'ganaha_hibiki': '我那霸响',
  'sagisawa_fumika': '�的�的文香',
  'mitake_ran': '美竹兰',
  'jougasaki_mika': '城崎美嘉',
  'anastasia_(idolmaster)': '安娜斯塔西亚',

  // BanG Dream!
  'togawa_sakiko': '户川纱希子',
  'chihaya_anon': '千早爱音',
  'nagasaki_soyo': '长崎素世',
  'shiina_taki': '椎名立希',
  'misumi_uika': '三角初华',
  'toyama_kasumi': '户山香澄',
  'hanazono_tae': '花园多惠',
  'ushigome_rimi': '牛込里美',
  'yamabuki_saaya': '山吹沙绫',
  'ichigaya_arisa': '市谷有咲',
  'hikawa_sayo': '冰川纱夜',
  'minato_yukina': '凑友希那',
  'imai_lisa': '今井莉纱',
  'udagawa_ako': '宇田川亚子',
  'shirokane_rinko': '白金燐子',

  // 魔法少女小圆
  'kaname_madoka': '鹿目圆',
  'akemi_homura': '晓美焰',
  'miki_sayaka': '美树沙耶加',
  'tomoe_mami': '巴麻美',
  'sakura_kyoko': '佐仓杏子',
  'momoe_nagisa': '百江渚',
  'tamaki_iroha': '环彩羽',
  'nanami_yachiyo': '七海八千代',
  'futaba_sana': '二叶纱那',
  'mitsuki_felicia': '深月菲莉希亚',
  'yui_(madoka_magica)': '由比',
  'charlotte_(madoka_magica)': '夏洛特',
  'ultimate_madoka': '究极圆神',
  'homulilly': '焰莉莉',
  'kyubey': '丘比',

  // EVA
  'souryuu_asuka_langley': '惣流·明日香·兰格雷',
  'ayanami_rei': '绫波丽',
  'ikari_shinji': '碇真嗣',
  'nagisa_kaworu': '渚薰',
  'makinami_mari_illustrious': '真希波·真理·伊拉丝多莉亚斯',
  'katsuragi_misato': '葛城美里',
  'ikari_gendou': '碇源堂',
  'akagi_ritsuko': '赤木律子',
  'ibuki_maya': '伊吹玛雅',
  'penpen': '企企',
  'eva_unit_01': 'EVA初号机',
  'eva_unit_02': 'EVA二号机',
  'eva_unit_00': 'EVA零号机',
  'rebuild_of_evangelion': '新剧场版',
  'sachiel': '萨基尔',

  // 龙珠
  'son_goku': '孙悟空',
  'vegeta': '贝吉塔',
  'android_18': '人造人18号',
  'bulma': '布尔玛',
  'son_gohan': '孙悟饭',
  'trunks': '特兰克斯',
  'piccolo': '比克',
  'krillin': '克林',
  'chi-chi': '琪琪',
  'frieza': '弗利萨',
  'cell_(dragon_ball)': '沙鲁',
  'videl': '比迪丽',
  'android_21': '人造人21号',
  'majin_buu': '魔人布欧',
  'goku_black': '黑悟空',

  // 进击的巨人
  'mikasa_ackerman': '三笠·阿克曼',
  'eren_yeager': '艾伦·耶格尔',
  'levi_(shingeki_no_kyojin)': '利威尔',
  'krista_lenz': '克里斯塔·伦茨',
  'armin_arlert': '阿尔敏·阿诺德',
  'sasha_braus': '莎夏·布劳斯',
  'annie_leonhart': '阿尼·莱昂哈特',
  'ymir_(shingeki_no_kyojin)': '尤弥尔',
  'hange_zoe': '韩吉·佐耶',
  'jean_kirschtein': '让·基尔希斯坦',
  'erwin_smith': '埃尔文·史密斯',
  'pieck_finger': '皮克·芬格尔',
  'gabi_braun': '贾碧·布朗',
  'reiner_braun': '莱纳·布朗',
  'petra_rall': '佩特拉·拉尔',

  // 崩坏3rd
  'elysia_(honkai_impact)': '爱莉希雅',
  'kiana_kaslana': '琪亚娜·卡斯兰娜',
  'raiden_mei': '雷电芽衣',
  'fu_hua': '符华',
  'elysia_(herrscher_of_human:_ego)_(honkai_impact)': '爱莉希雅(人之律者)',
  'bronya_zaychik': '布洛妮娅',
  'seele_vollerei': '希儿·芙乐艾',
  'rita_rossweisse': '丽塔·洛丝薇瑟',
  'durandal_(honkai_impact)': '幽兰黛尔',
  'yae_sakura_(honkai_impact)': '八重樱',
  'theresa_apocalypse': '德丽莎·阿波卡利斯',
  'himeko_murata': '无量塔姬子',
  'pardofelis_(honkai_impact)': '帕朵菲莉丝',
  'mobius_(honkai_impact)': '梅比乌斯',
  'aponia_(honkai_impact)': '阿波尼亚',

  // 少女前线
  "hk416_(girls'_frontline)": 'HK416',
  "ump45_(girls'_frontline)": 'UMP45',
  "wa2000_(girls'_frontline)": 'WA2000',
  "ump9_(girls'_frontline)": 'UMP9',
  "m4a1_(girls'_frontline)": 'M4A1',
  "st_ar-15_(girls'_frontline)": 'ST AR-15',
  "m4_sopmod_ii_(girls'_frontline)": 'M4 SOPMOD II',
  "m16a1_(girls'_frontline)": 'M16A1',
  "ro635_(girls'_frontline)": 'RO635',
  "g11_(girls'_frontline)": 'G11',
  "m200_(girls'_frontline)": 'M200',
  "ak-12_(girls'_frontline)": 'AK-12',
  "an-94_(girls'_frontline)": 'AN-94',
  "springfield_(girls'_frontline)": '春田',
  "kar98k_(girls'_frontline)": 'Kar98k',

  // 赛马娘
  'agnes_tachyon_(umamusume)': '亚克敦',
  'manhattan_cafe_(umamusume)': '曼哈顿咖啡',
  'gold_ship_(umamusume)': '黄金船',
  'rice_shower_(umamusume)': '米浴',
  'special_week_(umamusume)': '特别周',
  'tokai_teio_(umamusume)': '东海帝王',
  'symboli_rudolf_(umamusume)': '鲁道夫象征',
  'vodka_(umamusume)': '伏特加',
  'daiwa_scarlet_(umamusume)': '大和赤骥',
  'silence_suzuka_(umamusume)': '无声铃鹿',
  'mejiro_mcqueen_(umamusume)': '目白麦昆',
  'haru_urara_(umamusume)': '春丽',
  'oguri_cap_(umamusume)': '小栗帽',
  'kitasan_black_(umamusume)': '北部玄驹',
  'satono_diamond_(umamusume)': '里见光钻',

  // Lycoris Recoil
  'nishikigi_chisato': '�的足千束',
  'inoue_takina': '井之上�的奈',
  'kurumi_(lycoris_recoil)': '胡桃',
  'mizuki_(lycoris_recoil)': '瑞希',
  'fuki_(lycoris_recoil)': '吹',
  'sakura_(lycoris_recoil)': '樱',
  'erika_(lycoris_recoil)': '惠理香',
  'himegama_yoshimatsu_(lycoris_recoil)': '�的�的吉松',
  'mika_(lycoris_recoil)': '美佳',
  'majima_(lycoris_recoil)': '真岛',
  'robota_(lycoris_recoil)': '机器人太',
  'shinji_(lycoris_recoil)': '真司',
  'walnut_(lycoris_recoil)': '核桃',
  'himegama_(lycoris_recoil)': '姫釜',

  // 我的英雄学院
  'midoriya_izuku': '绿谷出久',
  'bakugou_katsuki': '爆豪胜己',
  'mirko': '米尔科',
  'uraraka_ochaco': '丽日御茶子',
  'toga_himiko': '渡我被身子',
  'todoroki_shouto': '�的冻焦凍',
  'yaoyorozu_momo': '八百万百',
  'asui_tsuyu': '蛙吹梅雨',
  'jirou_kyouka': '耳郎响香',
  'mt._lady': '大姐姐',
  'all_might': '欧尔麦特',
  'shigaraki_tomura': '死柄木弔',
  'eri_(boku_no_hero_academia)': '壊理',
  'midnight_(boku_no_hero_academia)': '午夜',
  'camie_utsushimi': '现见凯美',

  // 魔法禁书目录
  'misaka_mikoto': '御坂美琴',
  'shokuhou_misaki': '食蜂操祈',
  'saten_ruiko': '佐天泪子',
  'kamijou_touma': '上条当麻',
  'accelerator': '一方通行',
  'index_librorum_prohibitorum': '茵蒂克丝',
  'last_order': '最后之作',
  'misaka_worst': '御坂最恶',
  'shirai_kuroko': '白井黑子',
  'mugino_shizuri': '麦野�的琴',
  'othinus': '奥提努斯',
  'hamazura_shiage': '浜面仕上',
  'kakine_teitoku': '垣根帝督',
  'uiharu_kazari': '初春饰利',
  'itsuwa': '五和',

  // 约会大作战
  'tokisaki_kurumi': '时崎狂三',
  'tokisaki_kurumi_(spirit)': '时崎狂三(精灵)',
  'yatogami_tohka': '夜刀神十香',
  'itsuka_kotori': '五河琴里',
  'tobiichi_origami': '鸢一折纸',
  'yoshino_(date_a_live)': '四糸乃',
  'izayoi_miku': '诱宵美九',
  'natsumi_(date_a_live)': '七罪',
  'yamai_kaguya': '八舞耶俱矢',
  'yamai_yuzuru': '八舞夕弦',
  'itsuka_shidou': '五河士道',
  'hoshimiya_mukuro': '星宫六喰',
  'nia_honjou': '本条二亚',
  'takamiya_mio': '崇宫澪',

  // 公主连结
  'karyl_(princess_connect!)': '凯露',
  'kokkoro_(princess_connect!)': '可可萝',
  'pecorine_(princess_connect!)': '佩可莉姆',
  'saren_(princess_connect!)': '沙伦',
  'kyoka_(princess_connect!)': '镜华',
  'kyaru_(princess_connect!)': '凯露',
  'hatsune_(princess_connect!)': '初音',
  'suzume_(princess_connect!)': '铃莓',
  'mimi_(princess_connect!)': '美美',
  'yui_(princess_connect!)': '优衣',
  'rei_(princess_connect!)': '怜',
  'shiori_(princess_connect!)': '栞',
  'rino_(princess_connect!)': '璃乃',
  'akari_(princess_connect!)': '茜里',
  'misato_(princess_connect!)': '美里',

  // 迷宫饭
  'marcille_donato': '玛露希尔',
  'falin_touden': '法琳',
  'laios_touden': '莱欧斯',
  'senshi_(dungeon_meshi)': '千歲',
  'mithrun': '米斯伦',
  'chilchuck_tims': '齐尔查克',
  'izutsumi': '出�的美',
  'kabru': '卡布吕',
  'thistle_(dungeon_meshi)': '蓟',
  'yaad_(dungeon_meshi)': '亚德',

  // 葬送的芙莉莲
  'fern_(sousou_no_frieren)': '菲伦',
  'himmel_(sousou_no_frieren)': '欣梅尔',
  'stark_(sousou_no_frieren)': '修塔尔克',
  'aura_(sousou_no_frieren)': '奥拉',
  'flamme_(sousou_no_frieren)': '芙拉梅',
  'serie_(sousou_no_frieren)': '赛丽叶',
  'ubel_(sousou_no_frieren)': '于贝尔',
  'denken_(sousou_no_frieren)': '登肯',
  'linie_(sousou_no_frieren)': '莉涅',
  'lawine_(sousou_no_frieren)': '拉薇涅',
  'kanne_(sousou_no_frieren)': '卡恩妮',
  'frieren': '芙莉莲',

  // 无职转生
  'eris_greyrat': '艾莉丝·格雷拉特',
  'sylphiette_(mushoku_tensei)': '希露菲',
  'rudeus_greyrat': '鲁迪乌斯·格雷拉特',
  'ghislaine_dedoldia': '基列奴·德多鲁迪亚',
  'roxy_migurdia': '洛琦希·米格路迪亚',
  'paul_greyrat': '保罗·格雷拉特',
  'zenith_greyrat': '赛妮丝·格雷拉特',
  'elinalise_dragonroad': '艾丽娜莉洁',
  'nanahoshi_shizuka': '七星静香',

  // 紫罗兰永恒花园
  'violet_evergarden': '薇尔莉特·伊芙加登',
  'gilbert_bougainvillea': '吉尔伯特',
  'cattleya_baudelaire': '卡特莉雅',
  'claudia_hodgins': '克劳迪亚',
  'luculia_marlborough': '露库丽亚',
  'iris_(violet_evergarden)': '艾瑞丝',

  // 来自深渊
  'nanachi_(made_in_abyss)': '娜娜奇',
  'reg_(made_in_abyss)': '雷格',
  'faputa': '法普塔',
  'riko_(made_in_abyss)': '莉可',
  'ozen': '奥森',
  'bondrewd': '黎明卿',
  'prushka': '普鲁修卡',
  'vueko': '薇可',
  'lyza': '莱莎',

  // 尼尔
  '2b_(nier:automata)': '2B',
  '9s_(nier:automata)': '9S',
  'pod_(nier:automata)': 'Pod',
  'a2_(nier:automata)': 'A2',
  'kaine_(nier)': '凯妮',
  'nier_(nier)': '尼尔',
  'devola_(nier:automata)': '迪瓦拉',
  'popola_(nier:automata)': '波波拉',
  'commander_(nier:automata)': '指挥官',
  'emil_(nier)': '艾米尔',
  'devola_(nier)': '迪瓦拉',
  'popola_(nier)': '波波拉',
  'zero_(drakengard)': '零',
  'operator_6o_(nier:automata)': '6O',
  'operator_21o_(nier:automata)': '21O',

  // 最终幻想
  'warrior_of_light_(ff14)': '光之战士',
  'zack_fair': '扎克·菲尔',
  'squall_leonhart': '斯考尔·莱昂哈特',
  'tifa_lockhart': '蒂法·洛克哈特',
  'cloud_strife': '克劳德·斯特莱夫',
  'aerith_gainsborough': '爱丽丝·盖恩斯伯勒',
  'sephiroth': '萨菲罗斯',
  'lightning_(ff13)': '雷光',
  'yuna_(ff10)': '尤娜',
  'y\'shtola_rhul': '雅·修特拉',
  'minfilia_warde': '敏菲利亚',
  'alisaie_leveilleur': '阿莉塞',
  'rinoa_heartilly': '莉诺雅',
  'garnet_til_alexandros_xvii': '格奈特',
  'noctis_lucis_caelum': '诺克提斯',

  // 碧蓝幻想
  'djeeta_(granblue_fantasy)': '姬塔',
  'narmaya_(granblue_fantasy)': '娜尔梅亚',
  'gran_(granblue_fantasy)': '古兰',
  'zeta_(granblue_fantasy)': '泽塔',
  'anila_(granblue_fantasy)': '安妮拉',
  'vira_(granblue_fantasy)': '维拉',
  'beatrix_(granblue_fantasy)': '贝亚朵莉切',
  'cagliostro_(granblue_fantasy)': '卡里奥斯特罗',
  'lyria_(granblue_fantasy)': '露莉亚',
  'yuel_(granblue_fantasy)': '尤艾尔',
  'societte_(granblue_fantasy)': '索希艾特',
  'ilsa_(granblue_fantasy)': '伊尔莎',
  'jeanne_d\'arc_(granblue_fantasy)': '贞德',
  'ferry_(granblue_fantasy)': '菲莉',
  'io_(granblue_fantasy)': '伊奥',

  // 轻音少女
  'nakano_azusa': '中野梓',
  'tainaka_ritsu': '田井中律',
  'kotobuki_tsumugi': '琴吹䌷',
  'hirasawa_ui': '平�的唯',
  'manabe_nodoka': '真锅和',
  'suzuki_jun': '铃木�的',
  'yamanaka_sawako': '山中佐和子',
  'akiyama_mio': '秋山澪',
  'hirasawa_yui': '平泽唯',
  'ton-chan': '小唐',
  'saitou_sumire': '�的藤堇',
  'okada_haruna': '冈田晴菜',
  'tachibana_himeko': '橘姬子',
  'wakaouji_ichigo': '若王子一子',
  'nojima_chika': '野�的千佳',

  // 斩服少女
  'matoi_ryuuko': '缠流子',
  'senketsu': '�的血',
  'kiryuuin_satsuki': '鬼龙院皐月',
  'mankanshoku_mako': '满艦饰真子',
  'junketsu': '纯洁',
  'jakuzure_nonon': '蛇崩乃音',
  'inumuta_houka': '犬牟田宝火',
  'sanageyama_uzu': '猿投山�的',
  'gamagoori_ira': '蟇郡苛',
  'harime_nui': '针目�的',
  'kiryuuin_ragyo': '鬼龙院罗晓',
  'mikisugi_aikurou': '美木杉�的郎',
  'tsumugu_kinagase': '木流连',
  'iori_shirou': '伊织糸朗',
  'soroi_mitsuzo': '袭三藏',

  // 弹丸论破
  'nanami_chiaki': '七海千秋',
  'oma_kokichi': '王马小吉',
  'saihara_shuichi': '最原终一',
  'komaeda_nagito': '狛枝凪斗',
  'hinata_hajime': '日向创',
  'kirigiri_kyouko': '雾切响子',
  'naegi_makoto': '苗木诚',
  'junko_enoshima': '江之岛盾子',
  'togami_byakuya': '十神白夜',
  'sonia_nevermind': '索尼娅·内瓦敏德',
  'iruma_miu': '入间美兔',
  'akamatsu_kaede': '赤松枫',
  'celestia_ludenberg': '塞蕾丝缇亚',
  'tsumiki_mikan': '罪木蜜柑',
  'harukawa_maki': '春川魔姬',

  // 五等分的新娘
  'nakano_miku': '中野三玖',
  'nakano_yotsuba': '中野四叶',
  'nakano_itsuki': '中野五月',
  'nakano_ichika': '中野一花',
  'nakano_nino': '中野二乃',
  'uesugi_fuutarou': '上杉风太郎',
  'nakano_maruo': '中野丸男',
  'maeda_(go-toubun_no_hanayome)': '前田',
  'ebata_(go-toubun_no_hanayome)': '江畑',
  'shimoda_(go-toubun_no_hanayome)': '下田',
  'takebayashi_(go-toubun_no_hanayome)': '竹林',
  'takeda_(go-toubun_no_hanayome)': '武田',

  // 转生史莱姆
  'rimuru_tempest': '利姆鲁·坦派斯特',
  'shuna_(tensei_shitara_slime_datta_ken)': '朱菜',
  'shion_(tensei_shitara_slime_datta_ken)': '紫苑',
  'milim_nava': '米莉姆·纳瓦',
  'diablo_(tensei_shitara_slime_datta_ken)': '迪亚布罗',
  'benimaru_(tensei_shitara_slime_datta_ken)': '红丸',

  // 命运石之门
  'makise_kurisu': '牧瀬红莉栖',
  'okabe_rintarou': '冈部伦太郎',
  'shiina_mayuri': '椎名真由理',
  'hiyajou_maho': '比屋定真帆',
  'akiha_rumiho': '秋叶留未穗',
  'amane_suzuha': '阿万音铃羽',
  'hashida_itaru': '桥田至',
  'kiryu_moeka': '桐生萌郁',
  'urushibara_ruka': '漆原琉华',
  'tennouji_yuugo': '天王寺裕吾',
  'kagari_(steins;gate)': '篝',
  'tennouji_nae': '天王寺绹',
  'faris_nyannyan': '菲利斯·喵喵',
  'leskinen_(steins;gate)': '列斯基宁',
  'maho_(steins;gate)': '真帆',

  // 小林家的龙女仆
  'tohru_(maidragon)': '托尔',
  'lucoa_(maidragon)': '露科亚',
  'ilulu_(maidragon)': '伊露露',
  'kobayashi_(maidragon)': '小林',
  'elma_(maidragon)': '艾尔玛',
  'kanna_kamui': '康娜·卡穆伊',
  'fafnir_(maidragon)': '法夫尼尔',
  'takiya_makoto': '�的屋真',

  // 恶魔高校DxD
  'rias_gremory': '莉雅丝·吉蒙里',
  'himejima_akeno': '姬岛朱乃',
  'xenovia_quarta': '杰诺维亚·夸尔塔',
  'toujou_koneko': '塔城小猫',
  'asia_argento': '阿谢亚·阿洁特',
  'rossweisse': '洛丝维瑟',
  'irina_shidou': '紫藤伊莉娜',
  'grayfia_lucifuge': '格蕾菲亚·路西法格斯',
  'ravel_phenex': '雷薇儿·菲尼克斯',
  'hyoudou_issei': '�的堂诚二',
  'ophis_(high_school_dxd)': '奥菲斯',
  'le_fay_pendragon': '蕾·菲·潘德拉贡',
  'kuroka_(high_school_dxd)': '黑歌',
  'sona_sitri': '索娜·希特里',
  'serafall_leviathan': '瑟拉芙·利维坦',

  // DARLING in the FRANXX
  'zero_two_(darling_in_the_franxx)': '02(零二)',
  'hiro_(darling_in_the_franxx)': '016(广)',
  'ichigo_(darling_in_the_franxx)': '015(莓)',
  'kokoro_(darling_in_the_franxx)': '556(心)',
  'miku_(darling_in_the_franxx)': '390(未来)',
  'ikuno_(darling_in_the_franxx)': '196(郁乃)',
  'nana_(darling_in_the_franxx)': '七七',
  'goro_(darling_in_the_franxx)': '056(五郎)',
  'futoshi_(darling_in_the_franxx)': '214',

  // 绝区零
  'ellen_joe': '艾莲·乔',
  'belle_(zenless_zone_zero)': '绳匠(女)',
  'wise_(zenless_zone_zero)': '绳匠(男)',
  'hoshimi_miyabi': '星见雅',
  'jane_doe_(zenless_zone_zero)': '简·窦',
  'nicole_demara_(zenless_zone_zero)': '妮可·德玛拉',
  'anby_demara_(zenless_zone_zero)': '安比·德玛拉',
  'koleda_belobog_(zenless_zone_zero)': '可蕾达',
  'lycaon_(zenless_zone_zero)': '莱卡恩',
  'rina_(zenless_zone_zero)': '丽娜',
  'soukaku_(zenless_zone_zero)': '苍角',
  'nekomata_(zenless_zone_zero)': '猫又',
  'zhu_yuan_(zenless_zone_zero)': '朱鸢',
  'grace_howard_(zenless_zone_zero)': '格莉丝',
  'corin_wickes_(zenless_zone_zero)': '可琳',

  // 鸣潮
  'rover_(wuthering_waves)': '漂泊者',
  'zani_(wuthering_waves)': '赞妮',
  'male_rover_(wuthering_waves)': '漂泊者(男)',
  'female_rover_(wuthering_waves)': '漂泊者(女)',
  'changli_(wuthering_waves)': '长离',
  'jinhsi_(wuthering_waves)': '今汐',
  'yinlin_(wuthering_waves)': '吟霖',
  'shorekeeper_(wuthering_waves)': '守岸人',
  'camellya_(wuthering_waves)': '椿',
  'carlotta_(wuthering_waves)': '卡洛塔',
  'zhezhi_(wuthering_waves)': '折枝',
  'encore_(wuthering_waves)': '安可',
  'jiyan_(wuthering_waves)': '忌炎',
  'aalto_(wuthering_waves)': '秧秧',
  'sanhua_(wuthering_waves)': '散华',

  // 重返未来1999
  'vertin_(reverse:1999)': '维尔汀',
  'sonetto_(reverse:1999)': '十四行诗',
  '37_(reverse:1999)': '37',
  'isolde_(reverse:1999)': '伊索尔德',
  'regulus_(reverse:1999)': '轩辕',
  'centurion_(reverse:1999)': '百夫长',
  'tooth_fairy_(reverse:1999)': '牙仙',
  'medicine_pocket_(reverse:1999)': '药囊',
  'lilya_(reverse:1999)': '莉莉娅',
  'bkornblume_(reverse:1999)': '矢车菊',
  'sotheby_(reverse:1999)': '苏芙比',
  'pickles_(reverse:1999)': '皮克尔斯',
  'an-an_lee_(reverse:1999)': '安安李',
  'marcus_(reverse:1999)': '马库斯',
  'jessica_(reverse:1999)': '杰西卡',

  // Limbus Company
  'don_quixote_(project_moon)': '堂吉诃德',
  'ishmael_(project_moon)': '以实玛利',
  'faust_(project_moon)': '浮士德',
  'hong_lu_(project_moon)': '洪鲁',
  'sinclair_(project_moon)': '辛克莱',
  'heathcliff_(project_moon)': '希斯克利夫',
  'meursault_(project_moon)': '默尔索',
  'ryoshu_(project_moon)': '良秀',
  'outis_(project_moon)': '奥提斯',
  'rodion_(project_moon)': '罗季翁',
  'gregor_(project_moon)': '格里高尔',
  'yi_sang_(project_moon)': '李箱',
  'dante_(project_moon)': '但丁',
  'vergilius_(project_moon)': '维吉尔',
  'charon_(project_moon)': '卡戎',

  // 女神异闻录
  'narukami_yu': '�的上悠',
  'amamiya_ren': '雨宫莲',
  'yuuki_makoto_(persona_3)': '结城理',
  'shirogane_naoto': '白钟直斗',
  'satonaka_chie': '里中千枝',
  'amagi_yukiko': '天城雪子',
  'niijima_makoto': '新岛真',
  'takamaki_ann': '高卷杏',
  'kitagawa_yusuke': '喜多川祐介',
  'sakura_futaba': '佐仓双叶',
  'okumura_haru': '奥村春',
  'yoshizawa_kasumi': '芳�的霞',
  'aigis': '艾基斯',
  'morgana_(persona_5)': '摩尔加纳',
  'joker_(persona)': 'Joker',

  // Also expand existing ones that already have auto-names
  'reze_(chainsaw_man)': '蕾塞',
  'denji_(chainsaw_man)': '电次',
  'power_(chainsaw_man)': '帕瓦',
  'yoru_(chainsaw_man)': '夜',
  'himeno_(chainsaw_man)': '�的野',
  'asa_mitaka_(chainsaw_man)': '三鹰朝',
  'nayuta_(chainsaw_man)': '那由多',
  'kobeni_higashiyama': '东山小红',
  'kishibe_(chainsaw_man)': '岸边',
  'angel_devil': '天使恶魔',
  'quanxi': '光喜',
  'yoshida_hirofumi_(chainsaw_man)': '吉田�的文',

  'kita_ikuyo': '喜多郁代',
  'ijichi_nijika': '伊地知虹夏',
  'yamada_ryo': '山田凉',
  'hiroi_kikuri': '广井菊理',
  'pa-san_(bocchi_the_rock!)': 'PA先生',
  'seika_ijichi': '伊地知星歌',
  'kessoku_band': '结束乐队',
  'gotoh_futari': '后藤双叶',
  'eliza_shimizu': '清水伊丽莎',
  'shima_iwao': '志磨�的夫',
  'kikuri_hiroi': '廣井菊里',
  'gotoh_hitori': '后藤一里',

  'anya_(spy_x_family)': '阿尼亚',
  'twilight_(spy_x_family)': '黄昏',
  'damian_desmond': '达米安·戴斯蒙德',
  'bond_(spy_x_family)': '邦德',
  'fiona_frost': '菲奥娜·弗罗斯特',
  'becky_blackbell': '贝姬·布莱克贝尔',
  'handler_(spy_x_family)': '管理官',
  'franky_franklin': '弗兰基·富兰克林',
  'yuri_briar': '尤利·布莱尔',

  'hoshino_ai_(oshi_no_ko)': '星野爱',
  'arima_kana': '有马佳奈',
  'hoshino_ruby': '星野露比',
  'hoshino_aquamarine': '星野阿库亚',
  'kurokawa_akane': '黑川茜',
  'mem-cho': 'MEM酱',
  'airi_momobami': '桃园有栖',

  'anis_(nikke)': '安妮丝',
  'rapi_(nikke)': '拉比',
  'elegg_(nikke)': '艾蕾格',
  'cinderella_(nikke)': '灰姑娘',

  'kochou_shinobu': '蝴蝶忍',
  'tomioka_giyuu': '富冈义勇',
  'kamado_nezuko': '灶门祢豆子',
  'kanroji_mitsuri': '甘露寺蜜璃',
  'kamado_tanjirou': '灶门炭治郎',
  'rengoku_kyoujurou': '�的柱杏寿郎',
  'tokitou_muichirou': '时透无一郎',
  'agatsuma_zenitsu': '我妻善逸',

  'gojo_satoru': '五条悟',
  'itadori_yuji': '虎杖悠仁',
  'fushiguro_megumi': '伏黑惠',
  'geto_suguru': '夏油杰',
  'kugisaki_nobara': '釘崎野蔷薇',
  'zenin_maki': '禅院真希',
  'inumaki_toge': '狗卷棘',
  'todo_aoi': '东堂葵',

  'rem_(re:zero)': '蕾姆',
  'emilia_(re:zero)': '艾米莉亚',
  'ram_(re:zero)': '拉姆',
  'natsuki_subaru': '菜月昴',
  'beatrice_(re:zero)': '碧翠丝',
  'echidna_(re:zero)': '艾奇德娜',

  'asuna_(sao)': '亚丝娜',
  'kirito': '桐人',
  'sinon': '诗乃',
  'kirigaya_suguha': '桐谷直叶',
  'leafa_(sao)': '莉法',
  'yuuki_(sao)': '有纪',
  'alice_zuberg': '爱丽丝',
  'silica_(sao)': '西莉卡',
  'lisbeth_(sao)': '莉兹贝特',

  'nami_(one_piece)': '娜美',
  'monkey_d._luffy': '路飞',
  'nico_robin': '妮可·罗宾',
  'roronoa_zoro': '索隆',
  'sanji_(one_piece)': '山治',
  'boa_hancock': '波雅·汉库克',
  'portgas_d._ace': '波特卡斯·D·艾斯',
  'trafalgar_law': '特拉法尔加·罗',
  'vinsmoke_reiju': '温斯莫克·蕾玖',
  'perona': '佩罗娜',
  'yamato_(one_piece)': '大和',
  'carrot_(one_piece)': '加洛特',

  'uzumaki_naruto': '漩涡鸣人',
  'haruno_sakura': '春野樱',
  'hyuuga_hinata': '日向雏田',
  'uchiha_sasuke': '宇智波佐助',
  'tsunade_(naruto)': '纲手',
  'uchiha_itachi': '宇智波鼬',
  'hatake_kakashi': '旗木卡卡西',
  'temari': '手鞠',
  'konan_(naruto)': '小南',
  'ino_yamanaka': '山中井野',
  'jiraiya': '自来也',
  'gaara': '我爱罗',

  'hinoshita_kaho': '日下花帆',
  'nishikino_maki': '西木野真姬',
  'sonoda_umi': '园田海未',
  'yazawa_nico': '矢�的妮可',
  'ayase_eli': '绚濑绘里',
  'toujou_nozomi': '东条希',
  'kousaka_honoka': '高坂�的果',
  'minami_kotori': '南小鸟',
  'koizumi_hanayo': '小泉花阳',
  'hoshizora_rin': '星空凛',
  'sakurauchi_riko': '樱内梨子',
  'takami_chika': '高海千歌',

  'megumin_(konosuba)': '惠惠',
  'aqua_(konosuba)': '阿库娅',
  'satou_kazuma': '佐藤和真',
  'darkness_(konosuba)': '达克妮斯',
  'yunyun_(konosuba)': '芸芸',
  'wiz_(konosuba)': '薇兹',
};

const tagsData = JSON.parse(fs.readFileSync(path.join(__dirname, 'tags.json'), 'utf8'));
const group0 = tagsData['0'];

let translated = 0;
let total = 0;

for (const [idx, sg] of Object.entries(group0.subgroups)) {
  const i = parseInt(idx);
  if (i < 23 || !sg || !sg.tags) continue;

  for (const tag of sg.tags) {
    total++;
    const cnName = CN_NAMES[tag.t];
    if (cnName && tag.d !== cnName) {
      tag.d = cnName;
      translated++;
    }
  }
}

fs.writeFileSync(
  path.join(__dirname, 'tags.json'),
  JSON.stringify(tagsData, null, 2),
  'utf8'
);

console.log(`Translated ${translated}/${total} character names to Chinese`);

// Check remaining untranslated
let untranslated = [];
for (const [idx, sg] of Object.entries(group0.subgroups)) {
  const i = parseInt(idx);
  if (i < 23 || !sg || !sg.tags) continue;
  for (const tag of sg.tags) {
    if (!CN_NAMES[tag.t]) {
      untranslated.push(`${sg.name}: ${tag.t} -> ${tag.d}`);
    }
  }
}
if (untranslated.length > 0) {
  console.log(`\nUntranslated (${untranslated.length}):`);
  untranslated.forEach(u => console.log('  ' + u));
}
