const fs = require('fs');
const path = require('path');

// 作品系列翻译
const SERIES_NAMES = {
  "Fate": "命运",
  "Hololive": "Hololive",
  "Vocaloid": "Vocaloid",
  "Honkai": "崩坏",
  "LoveLive": "LoveLive!",
  "Nijisanji": "彩虹社",
  "Jojo No Kimyou Na Bouken": "JOJO的奇妙冒险",
  "Precure": "光之美少女",
  "Fate/grand Order": "命运-冠位指定",
  "Kemono Friends": "兽娘动物园",
  "Gundam": "高达",
  "Splatoon": "喷射战士",
  "Lyrical Nanoha": "魔法少女奈叶",
  "The Legend Of Zelda": "塞尔达传说",
  "Boku No Hero Academia": "我的英雄学院",
  "Suzumiya Haruhi No Yuuutsu": "凉宫春日的忧郁",
  "Toaru Majutsu No Index": "魔法禁书目录",
  "Mario": "马力欧",
  "Bishoujo Senshi Sailor Moon": "美少女战士",
  "Touken Ranbu": "刀剑乱舞",
  "Xenoblade Chronicles": "异度神剑",
  "Street Fighter": "街头霸王",
  "BanG Dream": "BanG Dream!",
  "World Witches Series": "强袭魔女",
  "Tales Of": "传说系列",
  "Project Moon": "月亮计划",
  "Omori": "奥日",
  "Guilty Gear": "罪恶装备",
  "Overwatch": "守望先锋",
  "Indie Virtual Youtuber": "独立虚拟主播",
  "Umineko No Naku Koro Ni": "海猫鸣泣之时",
  "Gochuumon Wa Usagi Desu Ka?": "请问您今天要来点兔子吗？",
  "Shingeki No Kyojin": "进击的巨人",
  "Ragnarok Online": "仙境传说",
  "Project Sekai": "世界计划 缤纷舞台！",
  "Re:Zero": "Re:从零开始的异世界生活",
  "Voiceroid": "VOICEROID",
  "Monogatari": "物语系列",
  "Marvel": "漫威",
  "Dragon Quest": "勇者斗恶龙",
  "Kirby": "星之卡比",
  "Code Geass": "反叛的鲁路修",
  "Lucky Star": "幸运星",
  "Mega Man": "洛克人",
  "Sonic": "索尼克",
  "Tengen Toppa Gurren Lagann": "天元突破红莲螺岩",
  "Higurashi No Naku Koro Ni": "寒蝉鸣泣之时",
  "Neptune": "海王星",
  "Digimon": "数码宝贝",
  "Saibou Shinkyoku": "细胞神曲",
  "Inazuma Eleven": "闪电十一人",
  "Blazblue": "苍翼默示录",
  "Bleach": "境·界",
  "Tokyo Afterschool Summoners": "东京放课后召唤师",
  "Macross": "超时空要塞",
  "Rwby": "RWBY",
  "Tiger & Bunny": "老虎和兔子",
  "Tsukihime": "月姬",
  "Rozen Maiden": "蔷薇少女",
  "Go-toubun No Hanayome": "五等分的新娘",
  "Osomatsu-san": "阿松",
  "Assault Lily": "突击莉莉",
  "Yuru Yuri": "摇曳百合",
  "Onii-chan Wa Oshimai!": "别当欧尼酱了！",
  "Axis Powers Hetalia": "黑塔利亚",
  "Utau": "UTAU",
  "Apex Legends": "Apex英雄",
  "Saki": "天才麻将少女",
  "Elsword": "艾尔之光",
  "The King Of Fighters": "拳皇",
  "Vampire (game)": "恶魔战士",
  "Watashi Ga Motenai No Wa Dou Kangaetemo Omaera Ga Warui!": "我不受欢迎，怎么想都是你们的错！",
  "Cardcaptor Sakura": "魔卡少女樱",
  "Kamen Rider": "假面骑士",
  "Dc Comics": "DC漫画",
  "Senran Kagura": "闪乱神乐",
  "Ensemble Stars!": "偶像梦幻祭",
  "Little Busters!": "小小克星！",
  "Punishing: Gray Raven": "战双帕弥什",
  "Queen's Blade": "女王之刃",
  "Helltaker": "地狱把妹王",
  "Kagerou Project": "阳炎计划",
  "Atelier": "工作室系列",
  "Ace Attorney": "逆转裁判",
  "Holostars": "Holostars",
  "Hibike! Euphonium": "吹响！上低音号",
  "Pretty Series": "美妙系列",
  "Gridman Universe": "古立特宇宙",
  "Angel Beats!": "Angel Beats!",
  "Eiyuu Densetsu": "英雄传说",
  "Girls Band Cry": "GIRLS BAND CRY",
  "Link! Like! Love Live!": "Link! Like! Love Live!",
  "Monster Hunter": "怪物猎人",
  "Disgaea": "魔界战记",
  "Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai": "我的妹妹哪有这么可爱！",
  "Aikatsu!": "偶像活动！",
  "DARLING in the FRANXX": "DARLING in the FRANXX",
  "To Heart": "同班同学",
  "Nanashi Inc.": "ななしinc.",
  "Clannad": "CLANNAD",
  "Resident Evil": "生化危机",
  "To Love-ru": "出包王女",
  "Fullmetal Alchemist": "钢之炼金术师",
  "Panty & Stocking With Garterbelt": "吊带袜天使",
  "Ranma 1/2": "乱马1/2",
  "Kingdom Hearts": "王国之心",
  "Skullgirls": "骷髅女孩",
  "One-punch Man": "一拳超人",
  "Undertale": "传说之下",
  "Last Origin": "最后生还者",
  "Hunter X Hunter": "全职猎人",
  "Vshojo": "VShojo",
  "Gintama": "银魂",
  "Len'en": "连缘",
  "Vspo!": "VSPO!",
  "Metroid": "银河战士",
  "Twisted Wonderland": "扭曲仙境",
  "Yuri!!! On Ice": "冰上的尤里",
  "Puyopuyo": "噗よ噗よ",
  "Houseki No Kuni": "宝石之国",
  "Golden Kamuy": "黄金神威",
  "Sekaiju No Meikyuu": "世界树的迷宫",
  "Little Witch Academia": "小魔女学园",
  "Dead Or Alive": "死或生",
  "Kaguya-sama Wa Kokurasetai ~tensai-tachi No Renai Zunousen~": "辉夜大小姐想让我告白",
  "Black Rock Shooter": "黑岩射手",
  "Machikado Mazoku": "街角魔族",
  "Zombie Land Saga": "佐贺偶像是传奇",
  "Tekken": "铁拳",
  "Touqi Guaitan": "头七怪谈",
  "Pikmin": "皮克敏",
  "Gakuen Idolmaster": "学园偶像大师",
  "Yurucamp": "摇曳露营",
  "Amagami": "圣诞之吻",
  "Warship Girls R": "战舰少女R",
  "Transformers": "变形金刚",
  "Mahou Sensei Negima!": "魔法老师",
  "Sono Bisque Doll Wa Koi Wo Suru": "更衣人偶坠入爱河",
  "Gegege No Kitarou": "鬼太郎",
  "Yahari Ore No Seishun Lovecome Wa Machigatteiru.": "我的青春恋爱物语果然有问题。",
  "Maria-sama Ga Miteru": "圣母在上",
  "Alice In Wonderland": "爱丽丝梦游仙境",
  "Os-tan": "OS娘",
  "Toradora!": "龙与虎",
  "Hyouka": "冰菓",
  "Dungeon Ni Deai Wo Motomeru No Wa Machigatteiru Darou Ka": "在地下城寻求邂逅是否搞错了什么",
  "Fatal Fury": "饿狼传说",
  "Needy Girl Overdose": "主播女孩重度依赖",
  "Luo Xiaohei Zhanji": "罗小黑战记",
  "Shoujo Kageki Revue Starlight": "少女☆歌剧 Revue Starlight",
  "Dokidoki! Precure": "心跳！光之美少女",
  "Sayonara Zetsubou Sensei": "再见！绝望先生",
  "Zero No Tsukaima": "零之使魔",
  "Infinite Stratos": "IS〈Infinite Stratos〉",
  "Monster Musume No Iru Nichijou": "魔物娘的同居日常",
  "Meitantei Conan": "名侦探柯南",
  "Aria (manga)": "水星领航员",
  "Puzzle & Dragons": "智龙迷城",
  "Chuunibyou Demo Koi Ga Shitai!": "中二病也要谈恋爱！",
  "Star Ocean": "星之海洋",
  "Fairy Tail": "妖精的尾巴",
  "Doki Doki Literature Club": "心跳文学部",
  "Haikyuu!!": "排球少年！！",
  "Senpai Ga Uzai Kouhai No Hanashi": "关于前辈很烦人的事",
  "Dark Souls": "黑暗之魂",
  "Animal Crossing": "动物森友会",
  "Boku Wa Tomodachi Ga Sukunai": "我的朋友很少",
  "Working!!": "迷糊餐厅",
  "Sanrio": "三丽鸥",
  "Path To Nowhere": "无期迷途",
  "Durarara!!": "无头骑士异闻录",
  "Happinesscharge Precure!": "Happinesscharge光之美少女！",
  "Shakugan No Shana": "灼眼的夏娜",
  "Nitroplus": "Nitro+",
  "Hidamari Sketch": "向阳素描",
  "Kid Icarus": "光神话 帕尔提娜之镜",
  "Eromanga Sensei": "埃罗芒阿老师",
  "Kanon": "Kanon",
  "Nichijou": "日常",
  "Phantasy Star": "梦幻之星",
  "Yume Nikki": "梦日记",
  "Devil May Cry": "鬼泣",
  "Metal Gear": "合金装备",
  "Azumanga Daioh": "阿滋漫画大王",
  "Dungeon And Fighter": "地下城与勇士",
  "Tokyo Ghoul": "东京喰种",
  "Kamitsubaki Studio": "神椿工作室",
  "Yuuki Bakuhatsu Bang Bravern": "勇气爆发Bang Bravern",
  "Cyberpunk": "赛博朋克",
  "Spice And Wolf": "狼与香辛料",
  "Super Robot Wars": "超级机器人大战",
};

const CN_NAMES = {
  // 舰队Collection
  'kaga_(kancolle)': '加贺',
  'shimakaze_(kancolle)': '岛风',
  'shigure_(kancolle)': '时雨',
  'hibiki_(kancolle)': '响',
  'akagi_(kancolle)': '赤城',
  'zuikaku_(kancolle)': '瑞鹤',
  'shoukaku_(kancolle)': '翔鹤',
  'kongou_(kancolle)': '金刚',
  'yamato_(kancolle)': '大和',
  'iowa_(kancolle)': '衣阿华',
  'kashima_(kancolle)': '鹿岛',
  'hamakaze_(kancolle)': '浜风',
  'prinz_eugen_(kancolle)': '欧根亲王',
  'atago_(kancolle)': '爱宕',
  'suzuya_(kancolle)': '铃谷',

  // 偶像大师
  'shibuya_rin': '涩谷凛',
  'higuchi_madoka': '樋口圆香',
  'kisaragi_chihaya': '如月千早',
  'hoshii_miki': '星井美希',
  'ichinose_shiki': '一之濑志希',
  'takagaki_kaede': '高垣枫',
  'nitta_minami': '新田美奈实',
  'shimamura_uzuki': '岛村卯月',
  'honda_mio': '本田未央',
  'shijou_takane': '四条贵音',
  'ganaha_hibiki': '我那霸响',
  'sagisawa_fumika': '鹭泽文香',
  'mitake_ran': '美竹兰',
  'jougasaki_mika': '城崎美嘉',
  'anastasia_(idolmaster)': '安娜斯塔西亚',

  // BanG Dream!
  'togawa_sakiko': '户川纱希子',
  'chihaya_anon': '千早爱音',
  'nagasaki_soyo': '长崎素世',
  'shiina_taki': '椎名立希',
  'misumi_uika': '三角初华',
  'toyama_kasumi': '户山香澄',
  'hanazono_tae': '花园多惠',
  'ushigome_rimi': '牛込里美',
  'yamabuki_saaya': '山吹沙绫',
  'ichigaya_arisa': '市谷有咲',
  'hikawa_sayo': '冰川纱夜',
  'minato_yukina': '凑友希那',
  'imai_lisa': '今井莉纱',
  'udagawa_ako': '宇田川亚子',
  'shirokane_rinko': '白金燐子',

  // 魔法少女小圆
  'kaname_madoka': '鹿目圆',
  'akemi_homura': '晓美焰',
  'miki_sayaka': '美树沙耶加',
  'tomoe_mami': '巴麻美',
  'sakura_kyoko': '佐仓杏子',
  'momoe_nagisa': '百江渚',
  'tamaki_iroha': '环彩羽',
  'nanami_yachiyo': '七海八千代',
  'futaba_sana': '二叶纱那',
  'mitsuki_felicia': '深月菲莉希亚',
  'yui_(madoka_magica)': '由比',
  'charlotte_(madoka_magica)': '夏洛特',
  'ultimate_madoka': '究极圆神',
  'homulilly': '焰莉莉',
  'kyubey': '丘比',

  // EVA
  'souryuu_asuka_langley': '惣流·明日香·兰格雷',
  'ayanami_rei': '绫波丽',
  'ikari_shinji': '碇真嗣',
  'nagisa_kaworu': '渚薰',
  'makinami_mari_illustrious': '真希波·真理·伊拉丝多莉亚斯',
  'katsuragi_misato': '葛城美里',
  'ikari_gendou': '碇源堂',
  'akagi_ritsuko': '赤木律子',
  'ibuki_maya': '伊吹玛雅',
  'penpen': 'Pen Pen',
  'eva_unit_01': 'EVA初号机',
  'eva_unit_02': 'EVA二号机',
  'eva_unit_00': 'EVA零号机',
  'rebuild_of_evangelion': '新剧场版',
  'sachiel': '萨基尔',

  // 龙珠
  'son_goku': '孙悟空',
  'vegeta': '贝吉塔',
  'android_18': '人造人18号',
  'bulma': '布尔玛',
  'son_gohan': '孙悟饭',
  'trunks': '特兰克斯',
  'piccolo': '比克',
  'krillin': '克林',
  'chi-chi': '琪琪',
  'frieza': '弗利萨',
  'cell_(dragon_ball)': '沙鲁',
  'videl': '比迪丽',
  'android_21': '人造人21号',
  'majin_buu': '魔人布欧',
  'goku_black': '黑悟空',

  // 进击的巨人
  'mikasa_ackerman': '三笠·阿克曼',
  'eren_yeager': '艾伦·耶格尔',
  'levi_(shingeki_no_kyojin)': '利威尔',
  'krista_lenz': '克里斯塔·伦茨',
  'armin_arlert': '阿尔敏·阿诺德',
  'sasha_braus': '莎夏·布劳斯',
  'annie_leonhart': '阿尼·莱昂哈特',
  'ymir_(shingeki_no_kyojin)': '尤弥尔',
  'hange_zoe': '韩吉·佐耶',
  'jean_kirschtein': '让·基尔希斯坦',
  'erwin_smith': '埃尔文·史密斯',
  'pieck_finger': '皮克·芬格尔',
  'gabi_braun': '贾碧·布朗',
  'reiner_braun': '莱纳·布朗',
  'petra_rall': '佩特拉·拉尔',

  // 崩坏3rd
  'elysia_(honkai_impact)': '爱莉希雅',
  'kiana_kaslana': '琪亚娜·卡斯兰娜',
  'raiden_mei': '雷电芽衣',
  'fu_hua': '符华',
  'elysia_(herrscher_of_human:_ego)_(honkai_impact)': '爱莉希雅(人之律者)',
  'bronya_zaychik': '布洛妮娅',
  'seele_vollerei': '希儿·芙乐艾',
  'rita_rossweisse': '丽塔·洛丝薇瑟',
  'durandal_(honkai_impact)': '幽兰黛尔',
  'yae_sakura_(honkai_impact)': '八重樱',
  'theresa_apocalypse': '德丽莎·阿波卡利斯',
  'himeko_murata': '无量塔姬子',
  'pardofelis_(honkai_impact)': '帕朵菲莉丝',
  'mobius_(honkai_impact)': '梅比乌斯',
  'aponia_(honkai_impact)': '阿波尼亚',

  // 少女前线
  "hk416_(girls'_frontline)": 'HK416',
  "ump45_(girls'_frontline)": 'UMP45',
  "wa2000_(girls'_frontline)": 'WA2000',
  "ump9_(girls'_frontline)": 'UMP9',
  "m4a1_(girls'_frontline)": 'M4A1',
  "st_ar-15_(girls'_frontline)": 'ST AR-15',
  "m4_sopmod_ii_(girls'_frontline)": 'M4 SOPMOD II',
  "m16a1_(girls'_frontline)": 'M16A1',
  "ro635_(girls'_frontline)": 'RO635',
  "g11_(girls'_frontline)": 'G11',
  "m200_(girls'_frontline)": 'M200',
  "ak-12_(girls'_frontline)": 'AK-12',
  "an-94_(girls'_frontline)": 'AN-94',
  "springfield_(girls'_frontline)": '春田',
  "kar98k_(girls'_frontline)": 'Kar98k',

  // 赛马娘
  'agnes_tachyon_(umamusume)': '爱丽速子',
  'manhattan_cafe_(umamusume)': '曼哈顿咖啡',
  'gold_ship_(umamusume)': '黄金船',
  'rice_shower_(umamusume)': '米浴',
  'special_week_(umamusume)': '特别周',
  'tokai_teio_(umamusume)': '东海帝王',
  'symboli_rudolf_(umamusume)': '鲁道夫象征',
  'vodka_(umamusume)': '伏特加',
  'daiwa_scarlet_(umamusume)': '大和赤骥',
  'silence_suzuka_(umamusume)': '无声铃鹿',
  'mejiro_mcqueen_(umamusume)': '目白麦昆',
  'haru_urara_(umamusume)': '春丽',
  'oguri_cap_(umamusume)': '小栗帽',
  'kitasan_black_(umamusume)': '北部玄驹',
  'satono_diamond_(umamusume)': '里见光钻',

  // Lycoris Recoil
  'nishikigi_chisato': '锦木千束',
  'inoue_takina': '井之上泷奈',
  'kurumi_(lycoris_recoil)': '胡桃',
  'mizuki_(lycoris_recoil)': '瑞希',
  'fuki_(lycoris_recoil)': '吹雪',
  'sakura_(lycoris_recoil)': '樱',
  'erika_(lycoris_recoil)': '惠梨香',
  'himegama_yoshimatsu_(lycoris_recoil)': '吉松信二',
  'mika_(lycoris_recoil)': '米卡',
  'majima_(lycoris_recoil)': '真岛',
  'robota_(lycoris_recoil)': '机器太',
  'shinji_(lycoris_recoil)': '真司',
  'walnut_(lycoris_recoil)': '核桃',
  'himegama_(lycoris_recoil)': '姫蒲',

  // 我的英雄学院
  'midoriya_izuku': '绿谷出久',
  'bakugou_katsuki': '爆豪胜己',
  'mirko': '米尔科',
  'uraraka_ochaco': '丽日御茶子',
  'toga_himiko': '渡我被身子',
  'todoroki_shouto': '轰焦冻',
  'yaoyorozu_momo': '八百万百',
  'asui_tsuyu': '蛙吹梅雨',
  'jirou_kyouka': '耳郎响香',
  'mt._lady': 'Mt. Lady',
  'all_might': '欧尔麦特',
  'shigaraki_tomura': '死柄木弔',
  'eri_(boku_no_hero_academia)': '坏理',
  'midnight_(boku_no_hero_academia)': '午夜',
  'camie_utsushimi': '现见凯美',

  // 魔法禁书目录
  'misaka_mikoto': '御坂美琴',
  'shokuhou_misaki': '食蜂操祈',
  'saten_ruiko': '佐天泪子',
  'kamijou_touma': '上条当麻',
  'accelerator': '一方通行',
  'index_librorum_prohibitorum': '茵蒂克丝',
  'last_order': '最后之作',
  'misaka_worst': '御坂最恶',
  'shirai_kuroko': '白井黑子',
  'mugino_shizuri': '麦野沈利',
  'othinus': '奥帝努斯',
  'hamazura_shiage': '滨面仕上',
  'kakine_teitoku': '垣根帝督',
  'uiharu_kazari': '初春饰利',
  'itsuwa': '五和',

  // 约会大作战
  'tokisaki_kurumi': '时崎狂三',
  'tokisaki_kurumi_(spirit)': '时崎狂三(精灵)',
  'yatogami_tohka': '夜刀神十香',
  'itsuka_kotori': '五河琴里',
  'tobiichi_origami': '鸢一折纸',
  'yoshino_(date_a_live)': '四糸乃',
  'izayoi_miku': '诱宵美九',
  'natsumi_(date_a_live)': '七罪',
  'yamai_kaguya': '八舞耶俱矢',
  'yamai_yuzuru': '八舞夕弦',
  'itsuka_shidou': '五河士道',
  'hoshimiya_mukuro': '星宫六喰',
  'nia_honjou': '本条二亚',
  'takamiya_mio': '崇宫澪',

  // 公主连结
  'karyl_(princess_connect!)': '凯露',
  'kokkoro_(princess_connect!)': '可可萝',
  'pecorine_(princess_connect!)': '佩可莉姆',
  'saren_(princess_connect!)': '咲恋',
  'kyoka_(princess_connect!)': '镜华',
  'kyaru_(princess_connect!)': '凯露',
  'hatsune_(princess_connect!)': '初音',
  'suzume_(princess_connect!)': '铃莓',
  'mimi_(princess_connect!)': '美美',
  'yui_(princess_connect!)': '优衣',
  'rei_(princess_connect!)': '怜',
  'shiori_(princess_connect!)': '栞',
  'rino_(princess_connect!)': '璃乃',
  'akari_(princess_connect!)': '茜里',
  'misato_(princess_connect!)': '美里',

  // 迷宫饭
  'marcille_donato': '玛露希尔',
  'falin_touden': '法琳',
  'laios_touden': '莱欧斯',
  'senshi_(dungeon_meshi)': '扇西',
  'mithrun': '米斯伦',
  'chilchuck_tims': '奇尔查克',
  'izutsumi': '伊津津美',
  'kabru': '卡布尔',
  'thistle_(dungeon_meshi)': '蓟',
  'yaad_(dungeon_meshi)': '亚阿德',

  // 葬送的芙莉莲
  'fern_(sousou_no_frieren)': '菲伦',
  'himmel_(sousou_no_frieren)': '欣梅尔',
  'stark_(sousou_no_frieren)': '修塔尔克',
  'aura_(sousou_no_frieren)': '断头台的奥拉',
  'flamme_(sousou_no_frieren)': '芙拉梅',
  'serie_(sousou_no_frieren)': '赛丽艾',
  'ubel_(sousou_no_frieren)': '尤贝尔',
  'denken_(sousou_no_frieren)': '邓肯',
  'linie_(sousou_no_frieren)': '莉妮耶',
  'lawine_(sousou_no_frieren)': '拉维涅',
  'kanne_(sousou_no_frieren)': '康涅',
  'frieren': '芙莉莲',

  // 无职转生
  'eris_greyrat': '艾莉丝·格雷拉特',
  'sylphiette_(mushoku_tensei)': '希露菲叶特',
  'rudeus_greyrat': '鲁迪乌斯·格雷拉特',
  'ghislaine_dedoldia': '基列奴·德多鲁迪亚',
  'roxy_migurdia': '洛琪希·米格路迪亚',
  'paul_greyrat': '保罗·格雷拉特',
  'zenith_greyrat': '塞妮丝·格雷拉特',
  'elinalise_dragonroad': '艾莉娜丽洁·杜拉冈罗德',
  'nanahoshi_shizuka': '七星静香',

  // 紫罗兰永恒花园
  'violet_evergarden': '薇尔莉特·伊芙加登',
  'gilbert_bougainvillea': '基尔伯特·布甘比利亚',
  'cattleya_baudelaire': '嘉德丽雅·波德莱尔',
  'claudia_hodgins': '克劳迪亚·霍金斯',
  'luculia_marlborough': '露库莉亚·玛尔伯勒',
  'iris_(violet_evergarden)': '爱丽丝·坎纳利',

  // 来自深渊
  'nanachi_(made_in_abyss)': '娜娜奇',
  'reg_(made_in_abyss)': '雷格',
  'faputa': '法普妲',
  'riko_(made_in_abyss)': '莉可',
  'ozen': '奥森',
  'bondrewd': '波多尔多',
  'prushka': '普鲁修卡',
  'vueko': '维可',
  'lyza': '莱莎',

  // 尼尔
  '2b_(nier:automata)': '2B',
  '9s_(nier:automata)': '9S',
  'pod_(nier:automata)': 'Pod 042/153',
  'a2_(nier:automata)': 'A2',
  'kaine_(nier)': '凯妮',
  'nier_(nier)': '尼尔',
  'devola_(nier:automata)': '迪瓦菈',
  'popola_(nier:automata)': '波波菈',
  'commander_(nier:automata)': '司令官',
  'emil_(nier)': '艾米尔',
  'zero_(drakengard)': '零',
  'operator_6o_(nier:automata)': '操作员6O',
  'operator_21o_(nier:automata)': '操作员21O',

  // 最终幻想
  'warrior_of_light_(ff14)': '光之战士',
  'zack_fair': '扎克斯·菲尔',
  'squall_leonhart': '斯考尔·莱昂哈特',
  'tifa_lockhart': '蒂法·洛克哈特',
  'cloud_strife': '克劳德·斯特莱夫',
  'aerith_gainsborough': '爱丽丝·盖恩斯伯勒',
  'sephiroth': '萨菲罗斯',
  'lightning_(ff13)': '雷霆',
  'yuna_(ff10)': '尤娜',
  'y\'shtola_rhul': '雅·修特拉',
  'minfilia_warde': '敏菲利亚·沃德',
  'alisaie_leveilleur': '阿莉塞·莱韦耶勒尔',
  'rinoa_heartilly': '莉诺雅·哈蒂莉',
  'garnet_til_alexandros_xvii': '嘉妮特·蒂尔·亚历山德罗斯17世',
  'noctis_lucis_caelum': '诺克提斯·路西斯·切拉姆',

  // 碧蓝幻想
  'djeeta_(granblue_fantasy)': '姬塔',
  'narmaya_(granblue_fantasy)': '娜尔梅亚',
  'gran_(granblue_fantasy)': '古兰',
  'zeta_(granblue_fantasy)': '泽塔',
  'anila_(granblue_fantasy)': '安チラ',
  'vira_(granblue_fantasy)': '维拉',
  'beatrix_(granblue_fantasy)': '贝阿朵莉丝',
  'cagliostro_(granblue_fantasy)': '卡莉欧斯托萝',
  'lyria_(granblue_fantasy)': '露莉亚',
  'yuel_(granblue_fantasy)': '尤艾尔',
  'societte_(granblue_fantasy)': '苏丝耶',
  'ilsa_(granblue_fantasy)': '伊尔莎',
  'jeanne_d\'arc_(granblue_fantasy)': '贞德',
  'ferry_(granblue_fantasy)': '菲莉',
  'io_(granblue_fantasy)': '伊欧',

  // 轻音少女
  'nakano_azusa': '中野梓',
  'tainaka_ritsu': '田井中律',
  'kotobuki_tsumugi': '琴吹紬',
  'hirasawa_ui': '平泽忧',
  'manabe_nodoka': '真锅和',
  'suzuki_jun': '铃木纯',
  'yamanaka_sawako': '山中佐和子',
  'akiyama_mio': '秋山澪',
  'hirasawa_yui': '平泽唯',
  'ton-chan': '小豚',
  'saitou_sumire': '斋藤堇',
  'okada_haruna': '冈田春菜',
  'tachibana_himeko': '橘姬子',
  'wakaouji_ichigo': '若王子一女',
  'nojima_chika': '野岛千佳',

  // 斩服少女
  'matoi_ryuuko': '缠流子',
  'senketsu': '鲜血',
  'kiryuuin_satsuki': '鬼龙院皐月',
  'mankanshoku_mako': '满舰饰真子',
  'junketsu': '纯洁',
  'jakuzure_nonon': '蛇崩乃音',
  'inumuta_houka': '犬牟田宝火',
  'sanageyama_uzu': '猿投山涡',
  'gamagoori_ira': '蟇郡苛',
  'harime_nui': '针目缝',
  'kiryuuin_ragyo': '鬼龙院罗晓',
  'mikisugi_aikurou': '美木杉爱九郎',
  'tsumugu_kinagase': '木长濑纺',
  'iori_shirou': '伊织糸郎',
  'soroi_mitsuzo': '揃三藏',

  // 弹丸论破
  'nanami_chiaki': '七海千秋',
  'oma_kokichi': '王马小吉',
  'saihara_shuichi': '最原终一',
  'komaeda_nagito': '狛枝凪斗',
  'hinata_hajime': '日向创',
  'kirigiri_kyouko': '雾切响子',
  'naegi_makoto': '苗木诚',
  'junko_enoshima': '江之岛盾子',
  'togami_byakuya': '十神白夜',
  'sonia_nevermind': '索尼娅·内瓦麦',
  'iruma_miu': '入间美兔',
  'akamatsu_kaede': '赤松枫',
  'celestia_ludenberg': '塞蕾丝缇雅·罗登贝克',
  'tsumiki_mikan': '罪木蜜柑',
  'harukawa_maki': '春川魔姬',

  // 五等分的新娘
  'nakano_miku': '中野三玖',
  'nakano_yotsuba': '中野四叶',
  'nakano_itsuki': '中野五月',
  'nakano_ichika': '中野一花',
  'nakano_nino': '中野二乃',
  'uesugi_fuutarou': '上杉风太郎',
  'nakano_maruo': '中野丸男',
  'maeda_(go-toubun_no_hanayome)': '前田',
  'ebata_(go-toubun_no_hanayome)': '江端',
  'shimoda_(go-toubun_no_hanayome)': '下田',
  'takebayashi_(go-toubun_no_hanayome)': '竹林',
  'takeda_(go-toubun_no_hanayome)': '武田',

  // 转生史莱姆
  'rimuru_tempest': '利姆路·坦派斯特',
  'shuna_(tensei_shitara_slime_datta_ken)': '朱菜',
  'shion_(tensei_shitara_slime_datta_ken)': '紫苑',
  'milim_nava': '米莉姆·纳瓦',
  'diablo_(tensei_shitara_slime_datta_ken)': '迪亚波罗',
  'benimaru_(tensei_shitara_slime_datta_ken)': '红丸',

  // 命运石之门
  'makise_kurisu': '牧濑红莉栖',
  'okabe_rintarou': '冈部伦太郎',
  'shiina_mayuri': '椎名真由理',
  'hiyajou_maho': '比屋定真帆',
  'akiha_rumiho': '秋叶留未穗',
  'amane_suzuha': '阿万音铃羽',
  'hashida_itaru': '桥田至',
  'kiryu_moeka': '桐生萌郁',
  'urushibara_ruka': '漆原琉华',
  'tennouji_yuugo': '天王寺裕吾',
  'kagari_(steins;gate)': '篝',
  'tennouji_nae': '天王寺绹',
  'faris_nyannyan': '菲利斯·喵喵',
  'leskinen_(steins;gate)': '莱斯基恩',
  'maho_(steins;gate)': '真帆',

  // 小林家的龙女仆
  'tohru_(maidragon)': '托尔',
  'lucoa_(maidragon)': '露科亚',
  'ilulu_(maidragon)': '伊露露',
  'kobayashi_(maidragon)': '小林',
  'elma_(maidragon)': '艾尔玛',
  'kanna_kamui': '康娜卡姆依',
  'fafnir_(maidragon)': '法夫纳',
  'takiya_makoto': '泷谷真',

  // 恶魔高校DxD
  'rias_gremory': '莉雅丝·吉蒙里',
  'himejima_akeno': '姬岛朱乃',
  'xenovia_quarta': '洁诺薇亚·夸尔塔',
  'toujou_koneko': '塔城小猫',
  'asia_argento': '爱莎·阿尔杰特',
  'rossweisse': '罗丝薇瑟',
  'irina_shidou': '紫藤伊莉娜',
  'grayfia_lucifuge': '古蕾菲亚·路西菲古斯',
  'ravel_phenex': '蕾薇儿·菲尼克斯',
  'hyoudou_issei': '兵藤一诚',
  'ophis_(high_school_dxd)': '奥菲斯',
  'le_fay_pendragon': '勒菲·潘德拉刚',
  'kuroka_(high_school_dxd)': '黑歌',
  'sona_sitri': '苍那·西迪',
  'serafall_leviathan': '塞拉芙尔·利维坦',

  // DARLING in the FRANXX
  'zero_two_(darling_in_the_franxx)': '02',
  'hiro_(darling_in_the_franxx)': '广',
  'ichigo_(darling_in_the_franxx)': '莓',
  'kokoro_(darling_in_the_franxx)': '心',
  'miku_(darling_in_the_franxx)': '未来',
  'ikuno_(darling_in_the_franxx)': '郁乃',
  'nana_(darling_in_the_franxx)': '七',
  'goro_(darling_in_the_franxx)': '五郎',
  'futoshi_(darling_in_the_franxx)': '太',

  // 绝区零
  'ellen_joe': '艾莲·乔',
  'belle_(zenless_zone_zero)': '贝尔',
  'wise_(zenless_zone_zero)': '怀斯',
  'hoshimi_miyabi': '星见雅',
  'jane_doe_(zenless_zone_zero)': '简·窦',
  'nicole_demara_(zenless_zone_zero)': '妮可·德玛拉',
  'anby_demara_(zenless_zone_zero)': '安比·德玛拉',
  'koleda_belobog_(zenless_zone_zero)': '可蕾妲·贝洛伯格',
  'lycaon_(zenless_zone_zero)': '莱卡恩',
  'rina_(zenless_zone_zero)': '丽娜',
  'soukaku_(zenless_zone_zero)': '苍角',
  'nekomata_(zenless_zone_zero)': '猫又',
  'zhu_yuan_(zenless_zone_zero)': '朱鸢',
  'grace_howard_(zenless_zone_zero)': '格莉丝·霍华德',
  'corin_wickes_(zenless_zone_zero)': '可琳·威克斯',

  // 鸣潮
  'rover_(wuthering_waves)': '漂泊者',
  'zani_(wuthering_waves)': '赞妮',
  'male_rover_(wuthering_waves)': '漂泊者(男)',
  'female_rover_(wuthering_waves)': '漂泊者(女)',
  'changli_(wuthering_waves)': '长离',
  'jinhsi_(wuthering_waves)': '今汐',
  'yinlin_(wuthering_waves)': '吟霖',
  'shorekeeper_(wuthering_waves)': '守岸人',
  'camellya_(wuthering_waves)': '椿',
  'carlotta_(wuthering_waves)': '卡洛塔',
  'zhezhi_(wuthering_waves)': '折枝',
  'encore_(wuthering_waves)': '安可',
  'jiyan_(wuthering_waves)': '忌炎',
  'aalto_(wuthering_waves)': '秧秧',
  'sanhua_(wuthering_waves)': '散华',

  // 重返未来1999
  'vertin_(reverse:1999)': '维尔汀',
  'sonetto_(reverse:1999)': '十四行诗',
  '37_(reverse:1999)': '37',
  'isolde_(reverse:1999)': '伊索尔德',
  'regulus_(reverse:1999)': '星锑',
  'centurion_(reverse:1999)': '百夫长',
  'tooth_fairy_(reverse:1999)': '牙仙',
  'medicine_pocket_(reverse:1999)': '药不然',
  'lilya_(reverse:1999)': '莉拉',
  'bkornblume_(reverse:1999)': '柏林以东',
  'sotheby_(reverse:1999)': '苏芙比',
  'pickles_(reverse:1999)': '皮克勒斯',
  'an-an_lee_(reverse:1999)': '安安',
  'marcus_(reverse:1999)': '马库斯',
  'jessica_(reverse:1999)': '杰西卡',

  // Limbus Company
  'don_quixote_(project_moon)': '堂吉诃德',
  'ishmael_(project_moon)': '以实玛利',
  'faust_(project_moon)': '浮士德',
  'hong_lu_(project_moon)': '鸿璐',
  'sinclair_(project_moon)': '辛克莱',
  'heathcliff_(project_moon)': '希斯克利夫',
  'meursault_(project_moon)': '默尔索',
  'ryoshu_(project_moon)': '良秀',
  'outis_(project_moon)': '奥提斯',
  'rodion_(project_moon)': '罗佳',
  'gregor_(project_moon)': '格里高尔',
  'yi_sang_(project_moon)': '李箱',
  'dante_(project_moon)': '但丁',
  'vergilius_(project_moon)': '维吉里乌斯',
  'charon_(project_moon)': '卡戎',

  // 女神异闻录
  'narukami_yu': '鸣上悠',
  'amamiya_ren': '雨宫莲',
  'yuuki_makoto_(persona_3)': '结城理',
  'shirogane_naoto': '白钟直斗',
  'satonaka_chie': '里中千枝',
  'amagi_yukiko': '天城雪子',
  'niijima_makoto': '新岛真',
  'takamaki_ann': '高卷杏',
  'kitagawa_yusuke': '喜多川祐介',
  'sakura_futaba': '佐仓双叶',
  'okumura_haru': '奥村春',
  'yoshizawa_kasumi': '芳泽霞',
  'aigis': '埃癸斯',
  'morgana_(persona_5)': '摩尔加纳',
  'joker_(persona)': 'Joker',

  // Also expand existing ones that already have auto-names
  'reze_(chainsaw_man)': '蕾塞',
  'denji_(chainsaw_man)': '电次',
  'power_(chainsaw_man)': '帕瓦',
  'yoru_(chainsaw_man)': '夜',
  'himeno_(chainsaw_man)': '姬野',
  'asa_mitaka_(chainsaw_man)': '三鹰朝',
  'nayuta_(chainsaw_man)': '那由多',
  'kobeni_higashiyama': '东山小红',
  'kishibe_(chainsaw_man)': '岸边',
  'angel_devil': '天使恶魔',
  'quanxi': '光熙',
  'yoshida_hirofumi_(chainsaw_man)': '吉田宽文',

  'kita_ikuyo': '喜多郁代',
  'ijichi_nijika': '伊地知虹夏',
  'yamada_ryo': '山田凉',
  'hiroi_kikuri': '广井菊理',
  'pa-san_(bocchi_the_rock!)': 'PAさん',
  'seika_ijichi': '伊地知星歌',
  'kessoku_band': '结束乐队',
  'gotoh_futari': '后藤二里',
  'eliza_shimizu': '清水伊莱莎',
  'shima_iwao': '志摩岩',
  'gotoh_hitori': '后藤一里',

  'anya_(spy_x_family)': '阿尼亚·福杰',
  'twilight_(spy_x_family)': '黄昏',
  'damian_desmond': '达米安·德斯蒙',
  'bond_(spy_x_family)': '邦德·福杰',
  'fiona_frost': '菲奥娜·弗洛斯特',
  'becky_blackbell': '贝姬·布莱克贝尔',
  'handler_(spy_x_family)': '西尔维娅·舍伍德',
  'franky_franklin': '弗兰基·富兰克林',
  'yuri_briar': '尤里·布莱尔',

  'hoshino_ai_(oshi_no_ko)': '星野爱',
  'arima_kana': '有马加奈',
  'hoshino_ruby': '星野瑠美衣',
  'hoshino_aquamarine': '星野爱久爱海',
  'kurokawa_akane': '黑川茜',
  'mem-cho': 'MEM啾',
  'airi_momobami': '桃喰爱莉',

  'anis_(nikke)': '阿尼斯',
  'rapi_(nikke)': '拉毗',
  'elegg_(nikke)': '艾列格',
  'cinderella_(nikke)': '辛德瑞拉',

  'kochou_shinobu': '蝴蝶忍',
  'tomioka_giyuu': '富冈义勇',
  'kamado_nezuko': '灶门祢豆子',
  'kanroji_mitsuri': '甘露寺蜜璃',
  'kamado_tanjirou': '灶门炭治郎',
  'rengoku_kyoujurou': '炼狱杏寿郎',
  'tokitou_muichirou': '时透无一郎',
  'agatsuma_zenitsu': '我妻善逸',

  'gojo_satoru': '五条悟',
  'itadori_yuji': '虎杖悠仁',
  'fushiguro_megumi': '伏黑惠',
  'geto_suguru': '夏油杰',
  'kugisaki_nobara': '钉崎野蔷薇',
  'zenin_maki': '禅院真希',
  'inumaki_toge': '狗卷棘',
  'todo_aoi': '东堂葵',

  'rem_(re:zero)': '雷姆',
  'emilia_(re:zero)': '爱蜜莉雅',
  'ram_(re:zero)': '拉姆',
  'natsuki_subaru': '菜月昴',
  'beatrice_(re:zero)': '碧翠丝',
  'echidna_(re:zero)': '艾姬多娜',

  'asuna_(sao)': '亚丝娜',
  'kirito': '桐人',
  'sinon': '诗乃',
  'kirigaya_suguha': '桐谷直叶',
  'leafa_(sao)': '莉法',
  'yuuki_(sao)': '优纪',
  'alice_zuberg': '爱丽丝·滋贝鲁库',
  'silica_(sao)': '西莉卡',
  'lisbeth_(sao)': '莉兹贝特',

  'nami_(one_piece)': '娜美',
  'monkey_d._luffy': '蒙奇·D·路飞',
  'nico_robin': '妮可·罗宾',
  'roronoa_zoro': '罗罗诺亚·索隆',
  'sanji_(one_piece)': '山治',
  'boa_hancock': '波雅·汉库克',
  'portgas_d._ace': '波特卡斯·D·艾斯',
  'trafalgar_law': '特拉法尔加·罗',
  'vinsmoke_reiju': '文斯莫克·蕾玖',
  'perona': '佩罗娜',
  'yamato_(one_piece)': '大和',
  'carrot_(one_piece)': '加洛特',

  'uzumaki_naruto': '漩涡鸣人',
  'haruno_sakura': '春野樱',
  'hyuuga_hinata': '日向雏田',
  'uchiha_sasuke': '宇智波佐助',
  'tsunade_(naruto)': '纲手',
  'uchiha_itachi': '宇智波鼬',
  'hatake_kakashi': '旗木卡卡西',
  'temari': '手鞠',
  'konan_(naruto)': '小南',
  'ino_yamanaka': '山中井野',
  'jiraiya': '自来也',
  'gaara': '我爱罗',

  'hinoshita_kaho': '日下花帆',
  'nishikino_maki': '西木野真姬',
  'sonoda_umi': '园田海未',
  'yazawa_nico': '矢泽妮可',
  'ayase_eli': '绚濑绘里',
  'toujou_nozomi': '东条希',
  'kousaka_honoka': '高坂穗乃果',
  'minami_kotori': '南小鸟',
  'koizumi_hanayo': '小泉花阳',
  'hoshizora_rin': '星空凛',
  'sakurauchi_riko': '樱内梨子',
  'takami_chika': '高海千歌',

  'megumin_(konosuba)': '惠惠',
  'aqua_(konosuba)': '阿库娅',
  'satou_kazuma': '佐藤和真',
  'darkness_(konosuba)': '达克妮斯',
  'yunyun_(konosuba)': '芸芸',
  'wiz_(konosuba)': '维兹',
};

const tagsData = JSON.parse(fs.readFileSync(path.join(__dirname, 'tags.json'), 'utf8'));
const group0 = tagsData['0'];

let translated = 0;
let total = 0;

function applySeriesTranslation() {
  for (const [key, subgroup] of Object.entries(group0.subgroups)) {
    if (subgroup.name in SERIES_NAMES) {
      subgroup.name = SERIES_NAMES[subgroup.name];
    }
  }
}

applySeriesTranslation();

for (const [idx, sg] of Object.entries(group0.subgroups)) {
  const i = parseInt(idx);
  // a few are not characters series
  if (i < 23 || !sg || !sg.tags) continue;

  for (const tag of sg.tags) {
    total++;
    const cnName = CN_NAMES[tag.t];
    if (cnName && tag.d !== cnName) {
      tag.d = cnName;
      translated++;
    }
  }
}

fs.writeFileSync(
  path.join(__dirname, 'tags.json'),
  JSON.stringify(tagsData, null, 2),
  'utf8'
);

console.log(`Translated ${translated}/${total} character names to Chinese`);

// Check remaining untranslated
let untranslated = [];
for (const [idx, sg] of Object.entries(group0.subgroups)) {
  const i = parseInt(idx);
  if (i < 23 || !sg || !sg.tags) continue;
  for (const tag of sg.tags) {
    if (!CN_NAMES[tag.t]) {
      untranslated.push(`${sg.name}: ${tag.t} -> ${tag.d}`);
    }
  }
}
if (untranslated.length > 0) {
  console.log(`\nUntranslated (${untranslated.length}):`);
  // untranslated.forEach(u => console.log('  ' + u));
}

function checkUntranslatedSeries() {
  console.log('\n========================================');
  console.log('正在检查未翻译的作品系列名...');

  try {
    const tagsData = JSON.parse(fs.readFileSync(path.join(__dirname, 'tags.json'), 'utf8'));
    const group0 = tagsData['0'];

    if (!group0 || !group0.subgroups) {
      console.error("错误：在 'tags.json' 中找不到作品系列数据 (group '0')。");
      return;
    }

    const allSeriesNames = Object.values(group0.subgroups)
      .filter(sg => sg && sg.name)
      .map(sg => sg.name);
      
    const translatedSeriesValues = new Set(Object.values(SERIES_NAMES));
    const translatedSeriesKeys = new Set(Object.keys(SERIES_NAMES));

    const untranslated = allSeriesNames.filter(name => {
      // 如果名字本身就是中文，或者在翻译词典的key或value里，则认为是已翻译
      const isChinese = /[\u4e00-\u9fa5]/.test(name);
      return !isChinese && !translatedSeriesKeys.has(name) && !translatedSeriesValues.has(name);
    });

    if (untranslated.length > 0) {
      console.log(`\n发现 ${untranslated.length} 个未翻译的作品系列:`);
      untranslated.forEach(name => console.log(`  - ${name}`));
      // 将未翻译的列表写入文件
      fs.writeFileSync(path.join(__dirname, 'untranslated_series.txt'), untranslated.join('\n'), 'utf8');
      console.log('\n未翻译的系列名列表已保存到 untranslated_series.txt');
    } else {
      console.log('\n恭喜！所有作品系列名都已翻译或本身就是中文。');
    }

  } catch (error) {
    console.error('检查作品系列翻译时发生错误:', error);
  }
}

// 运行检查
// checkUntranslatedSeries();
